version: "3"

services:
  message-sending-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_HOST: 0.0.0.0
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis:6379
      WEBHOOK_URL: https://webhook.site/655d89ba-ac53-40a9-b9d0-2adf9f11775c
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - message-service-network

  postgres:
    image: postgres:14-alpine
    container_name: message-sending-service-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - message-service-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d database'"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: message-sending-service-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - message-service-network

networks:
  message-service-network:
